// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Chat Rss",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Chat Rss",
            targets: ["AppModule"],
            teamIdentifier: "RB3C4E5DEJ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .chatMessage),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .incomingNetworkConnections(),
                .outgoingNetworkConnections(),
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readWrite)
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/nmdias/FeedKit", "9.1.2"..<"10.0.0"),
        .package(url: "https://github.com/NuPlay/RichText.git", "2.2.0"..<"3.0.0"),
        .package(url: "https://github.com/onevcat/Kingfisher.git", "7.6.2"..<"8.0.0"),
        .package(url: "https://github.com/realm/realm-swift", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FeedKit", package: "FeedKit"),
                .product(name: "RichText", package: "RichText"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "RealmSwift", package: "realm-swift")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)